<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MasterListFunction;

class MasterListFunctionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'masterlist_module_type_id' => 1,
                'masterlist_function_type_id' => 1,
                'function_name' => 'Login Basic Authentication',
                'ox' => 1,
                'screen_count' => 1.00,
                'acceptance_criteria' => 'Handle Errors, Success Confirmation, Login Records',
                'uiux_md' => 0.25,
                'design_creation_md' =>  0.25,
                'development_md' => 1.00,
                'qa_testing_md' => 0.25,
                'qa_testing_responsive_md' => 0.13,
                'translation_md' => 0.13,
            ],
            [
                'masterlist_module_type_id' => 1,
                'masterlist_function_type_id' => 1,
                'function_name' => 'Login External Service Authentication',
                'ox' => null,
                'screen_count' => 0.5,
                'acceptance_criteria' => 'Handle Errors, Success Confirmation, Login Records',
                'uiux_md' => 0.25,
                'design_creation_md' =>  0.25,
                'development_md' => 0.75,
                'qa_testing_md' => 0.13,
                'qa_testing_responsive_md' => 0.06,
                'translation_md' => 0.06,
            ],
            [
                'masterlist_module_type_id' => 1,
                'masterlist_function_type_id' => 1,
                'function_name' => 'Login using SNS',
                'ox' => 1,
                'screen_count' => 0.5,
                'acceptance_criteria' => '1 SNS only',
                'uiux_md' => 0.25,
                'design_creation_md' =>  0.25,
                'development_md' => 0.75,
                'qa_testing_md' => 0.09,
                'qa_testing_responsive_md' => 0.06,
                'translation_md' => 0.06,
            ],
            [
                'masterlist_module_type_id' => 1,
                'masterlist_function_type_id' => 1,
                'function_name' => 'Login verification via OTP',
                'ox' => null,
                'screen_count' => 0.5,
                'acceptance_criteria' => 'Handle Errors, Success Confirmation, Login Records',
                'uiux_md' => 0.00,
                'design_creation_md' =>  0.25,
                'development_md' => 0.75,
                'qa_testing_md' => 0.09,
                'qa_testing_responsive_md' => 0.06,
                'translation_md' => 0.06,
            ],
            [
                'masterlist_module_type_id' => 1,
                'masterlist_function_type_id' => 1,
                'function_name' => 'Remember Me',
                'ox' => 1,
                'screen_count' => null,
                'acceptance_criteria' => 'Handle Errors, Cookie Settings and Expiration',
                'uiux_md' => 0.00,
                'design_creation_md' =>  0.25,
                'development_md' => 0.50,
                'qa_testing_md' => 0.09,
                'qa_testing_responsive_md' => 0.06,
                'translation_md' => 0.00,
            ],
            [
                'masterlist_module_type_id' => 1,
                'masterlist_function_type_id' => 1,
                'function_name' => 'Single Sign-On',
                'ox' => null,
                'screen_count' => null,
                'acceptance_criteria' => 'Handle Errors, Success Confirmation, Login Records',
                'uiux_md' => 0.13,
                'design_creation_md' =>  0.13,
                'development_md' => 1.00,
                'qa_testing_md' => 0.09,
                'qa_testing_responsive_md' => 0.06,
                'translation_md' => 0.00,
            ],
            [
                'masterlist_module_type_id' => 1,
                'masterlist_function_type_id' => 2,
                'function_name' => 'Manual Logout',
                'ox' => 1,
                'screen_count' => 0.5,
                'acceptance_criteria' => 'Handle Errors, Success Confirmation, Logout Records',
                'uiux_md' => 0.13,
                'design_creation_md' =>  0.50,
                'development_md' => 0.50,
                'qa_testing_md' => 0.13,
                'qa_testing_responsive_md' => 0.06,
                'translation_md' => 0.06,
            ],
            [
                'masterlist_module_type_id' => 1,
                'masterlist_function_type_id' => 2,
                'function_name' => 'Session Expiration',
                'ox' => 1,
                'screen_count' => null,
                'acceptance_criteria' => 'Session Settings',
                'uiux_md' => 0.38,
                'design_creation_md' =>  0.38,
                'development_md' => 0.25,
                'qa_testing_md' => 0.06,
                'qa_testing_responsive_md' => 0.31,
                'translation_md' => 0.00,
            ],
            [
                'masterlist_module_type_id' => 1,
                'masterlist_function_type_id' => 3,
                'function_name' => 'Forgot Password',
                'ox' => 1,
                'screen_count' => 0.5,
                'acceptance_criteria' => 'Input Email Modal, Set New Password Modal, Send Verification Code/Link via mail/sms, Verify Code and Update Password',
                'uiux_md' => 0.75,
                'design_creation_md' =>  0.75,
                'development_md' => 1.50,
                'qa_testing_md' => 0.51,
                'qa_testing_responsive_md' => 0.245,
                'translation_md' => 0.06,
            ],
            [
                'masterlist_module_type_id' => 1,
                'masterlist_function_type_id' => 4,
                'function_name' => 'Basic Information Input Page',
                'ox' => 2.0,
                'screen_count' => 0.5,
                'acceptance_criteria' => 'Handle Errors, Success Confirmation, Login Records',
                'uiux_md' => 0.38,
                'design_creation_md' =>  0.50,
                'development_md' => 1.00,
                'qa_testing_md' => 0.75,
                'qa_testing_responsive_md' => 0.50,
                'translation_md' => 0.38,
            ],
            [
                'masterlist_module_type_id' => 1,
                'masterlist_function_type_id' => 4,
                'function_name' => 'Send Email Verification Link and Registration Completion Mail',
                'ox' => 1,
                'screen_count' => null,
                'acceptance_criteria' => 'Send Email Verification Link and Registration Completion Mail',
                'uiux_md' => 0.25,
                'design_creation_md' =>  0.25,
                'development_md' => 0.50,
                'qa_testing_md' => 0.25,
                'qa_testing_responsive_md' => 0.13,
                'translation_md' => 0.00,
            ],
            [
                'masterlist_module_type_id' => 1,
                'masterlist_function_type_id' => 4,
                'function_name' => 'Sign-up via SNS',
                'ox' => 1,
                'screen_count' => 1.0,
                'acceptance_criteria' => 'Sign-up via SNS',
                'uiux_md' => 0.25,
                'design_creation_md' =>  0.50,
                'development_md' => 0.75,
                'qa_testing_md' => 0.38,
                'qa_testing_responsive_md' => 0.19,
                'translation_md' => 0.13,
            ],
            [
                'masterlist_module_type_id' => 1,
                'masterlist_function_type_id' => 5,
                'function_name' => 'App Settings: Profile',
                'ox' => 1,
                'screen_count' => 2.0,
                'acceptance_criteria' => 'Basic Information View/Edit Profile Page',
                'uiux_md' => 0.38,
                'design_creation_md' =>  0.50,
                'development_md' => 1.50,
                'qa_testing_md' => 0.75,
                'qa_testing_responsive_md' => 0.50,
                'translation_md' => 0.38,
            ],
            [
                'masterlist_module_type_id' => 1,
                'masterlist_function_type_id' => 6,
                'function_name' => 'App Settings: Change Password',
                'ox' => 1,
                'screen_count' => 1,
                'acceptance_criteria' => 'Input Current and New/Confirmed Password Input Fields, Verify and Update Password, Success Change Password Modal, Send Change Password Confirmation via Email',
                'uiux_md' => 0.51,
                'design_creation_md' =>  1.64,
                'development_md' => 1.63,
                'qa_testing_md' => 0.66,
                'qa_testing_responsive_md' => 0.37,
                'translation_md' => 0.09,
            ],
            [
                'masterlist_module_type_id' => 1,
                'masterlist_function_type_id' => 7,
                'function_name' => 'App Settings: Change Email',
                'ox' => 1,
                'screen_count' => 1.0,
                'acceptance_criteria' => 'New Email Input Field; Send Verification Link to New Email; Success Change Email Modal',
                'uiux_md' => 0.51,
                'design_creation_md' =>  1.14,
                'development_md' => 1.01,
                'qa_testing_md' => 0.43,
                'qa_testing_responsive_md' => 0.25,
                'translation_md' => 0.06,
            ],
            [
                'masterlist_module_type_id' => 1,
                'masterlist_function_type_id' => 8,
                'function_name' => 'App Settings: Notification',
                'ox' => 1,
                'screen_count' => 0.5,
                'acceptance_criteria' => 'Notification via App (Push, Badge);Send Notification via Email;Send Notification via SMS;Notification List, Read/Unread;Data Retention Settings',
                'uiux_md' => 1.25,
                'design_creation_md' =>  2.26,
                'development_md' => 3.25,
                'qa_testing_md' => 0.65,
                'qa_testing_responsive_md' => 0.30,
                'translation_md' => 0.13,
            ],
            [
                'masterlist_module_type_id' => 2,
                'masterlist_function_type_id' => 9,
                'function_name' => null,
                'ox' => 1,
                'screen_count' => null,
                'acceptance_criteria' => 'Internal processes only; check status, update status, contact 3rd party',
                'uiux_md' => 0.00,
                'design_creation_md' =>  0.31,
                'development_md' => 1.50,
                'qa_testing_md' => 0.50,
                'qa_testing_responsive_md' => 0.25,
                'translation_md' => 0.00,
            ],
            [
                'masterlist_module_type_id' => 2,
                'masterlist_function_type_id' => 10,
                'function_name' => null,
                'ox' => 1,
                'screen_count' => 1.0,
                'acceptance_criteria' => 'Data display based on logic forwarded by its equivalent BE/API function.',
                'uiux_md' => 0.38,
                'design_creation_md' =>  0.31,
                'development_md' => 1.50,
                'qa_testing_md' => 0.50,
                'qa_testing_responsive_md' => 0.25,
                'translation_md' => 0.25,
            ],
            [
                'masterlist_module_type_id' => 2,
                'masterlist_function_type_id' => 11,
                'function_name' => null,
                'ox' => 1,
                'screen_count' => 2.0,
                'acceptance_criteria' => 'Frontend+Backend, Retrieve, Process and Display data',
                'uiux_md' => 0.38,
                'design_creation_md' =>  0.63,
                'development_md' => 1.50,
                'qa_testing_md' => 0.50,
                'qa_testing_responsive_md' => 0.25,
                'translation_md' => 0.38,
            ],
            [
                'masterlist_module_type_id' => 1,
                'masterlist_function_type_id' => 12,
                'function_name' => 'Login verification via OTP',
                'ox' => 1,
                'screen_count' => 0.5,
                'acceptance_criteria' => 'Role Selection (checkbox)',
                'uiux_md' => 0.25,
                'design_creation_md' =>  0.50,
                'development_md' => 1.00,
                'qa_testing_md' => 0.50,
                'qa_testing_responsive_md' => 0.25,
                'translation_md' => 0.06,
            ],
            [
                'masterlist_module_type_id' => 1,
                'masterlist_function_type_id' => 12,
                'function_name' => 'List and Search',
                'ox' => null,
                'screen_count' => 1.0,
                'acceptance_criteria' => 'Search and List View, Enable / Disable Role, Delete',
                'uiux_md' => 0.38,
                'design_creation_md' =>  0.63,
                'development_md' => 1.00,
                'qa_testing_md' => 0.19,
                'qa_testing_responsive_md' => 0.09,
                'translation_md' => 0.25,
            ],
            [
                'masterlist_module_type_id' => 1,
                'masterlist_function_type_id' => 12,
                'function_name' => 'CRUD',
                'ox' => 1,
                'screen_count' => 3.0,
                'acceptance_criteria' => 'Add: Basic Fields with Profile Picture upload;Edit/View;Batch Delete',
                'uiux_md' => 0.51,
                'design_creation_md' =>  1.76,
                'development_md' => 3.01,
                'qa_testing_md' => 1.56,
                'qa_testing_responsive_md' => 1.03,
                'translation_md' => 0.50,
            ],
            [
                'masterlist_module_type_id' => 1,
                'masterlist_function_type_id' => 12,
                'function_name' => 'Import CSV',
                'ox' => 1,
                'screen_count' => null,
                'acceptance_criteria' => 'Handle Errors, Import Summary Display, Fixed Template',
                'uiux_md' => 0.25,
                'design_creation_md' =>  0.63,
                'development_md' => 1.00,
                'qa_testing_md' => 0.25,
                'qa_testing_responsive_md' => 0.13,
                'translation_md' => 0.00,
            ],
            [
                'masterlist_module_type_id' => 1,
                'masterlist_function_type_id' => 12,
                'function_name' => 'Export CSV',
                'ox' => 1,
                'screen_count' => null,
                'acceptance_criteria' => 'Handle Errors, Export Summary Display, Fixed Template',
                'uiux_md' => 0.25,
                'design_creation_md' =>  0.63,
                'development_md' => 0.75,
                'qa_testing_md' => 0.25,
                'qa_testing_responsive_md' => 0.13,
                'translation_md' => 0.00,
            ],
            [
                'masterlist_module_type_id' => 3,
                'masterlist_function_type_id' => 13,
                'function_name' => 'Data Analysis (Graphical View)',
                'ox' => 1,
                'screen_count' => 1.0,
                'acceptance_criteria' => null,
                'uiux_md' => 0.38,
                'design_creation_md' =>  0.88,
                'development_md' => 1.25,
                'qa_testing_md' => 0.63,
                'qa_testing_responsive_md' => 0.31,
                'translation_md' => 0.25,
            ],
            [
                'masterlist_module_type_id' => 3,
                'masterlist_function_type_id' => 13,
                'function_name' => 'Data Analysis (Summary Count and Table View)',
                'ox' => 1,
                'screen_count' => 0.5,
                'acceptance_criteria' => null,
                'uiux_md' => 0.38,
                'design_creation_md' =>  0.88,
                'development_md' => 0.75,
                'qa_testing_md' => 0.63,
                'qa_testing_responsive_md' => 0.31,
                'translation_md' => 0.13,
            ],
            [
                'masterlist_module_type_id' => 3,
                'masterlist_function_type_id' => 13,
                'function_name' => 'Calendar with event view',
                'ox' => 1,
                'screen_count' => 1.0,
                'acceptance_criteria' => null,
                'uiux_md' => 0.38,
                'design_creation_md' =>  0.88,
                'development_md' => 1.25,
                'qa_testing_md' => 0.63,
                'qa_testing_responsive_md' => 0.31,
                'translation_md' => 0.25,
            ],
            [
                'masterlist_module_type_id' => 3,
                'masterlist_function_type_id' => 13,
                'function_name' => 'List Display',
                'ox' => 1,
                'screen_count' => 1.0,
                'acceptance_criteria' => null,
                'uiux_md' => 0.38,
                'design_creation_md' =>  0.63,
                'development_md' => 1.00,
                'qa_testing_md' => 0.38,
                'qa_testing_responsive_md' => 0.19,
                'translation_md' => 0.25,
            ],
            [
                'masterlist_module_type_id' => 3,
                'masterlist_function_type_id' => 13,
                'function_name' => 'To Do List/CRUD',
                'ox' => 1,
                'screen_count' => 1.0,
                'acceptance_criteria' => null,
                'uiux_md' => 0.38,
                'design_creation_md' =>  0.63,
                'development_md' => 0.75,
                'qa_testing_md' => 0.25,
                'qa_testing_responsive_md' => 0.13,
                'translation_md' => 0.25,
            ],
            [
                'masterlist_module_type_id' => 4,
                'masterlist_function_type_id' => 14,
                'function_name' => 'Search, List, Delete',
                'ox' => 1,
                'screen_count' => 1.0,
                'acceptance_criteria' => 'Includes  List, Search, Sorting',
                'uiux_md' => 0.50,
                'design_creation_md' =>  0.50,
                'development_md' => 1.00,
                'qa_testing_md' => 0.50,
                'qa_testing_responsive_md' => 0.25,
                'translation_md' => 0.25,
            ],
            [
                'masterlist_module_type_id' => 4,
                'masterlist_function_type_id' => 14,
                'function_name' => 'Add',
                'ox' => 1,
                'screen_count' => 1.0,
                'acceptance_criteria' => null,
                'uiux_md' => 0.50,
                'design_creation_md' =>  0.50,
                'development_md' => 1.00,
                'qa_testing_md' => 0.50,
                'qa_testing_responsive_md' => 0.25,
                'translation_md' => 0.25,
            ],
            [
                'masterlist_module_type_id' => 4,
                'masterlist_function_type_id' => 14,
                'function_name' => 'Edit/View',
                'ox' => 1,
                'screen_count' => 1.0,
                'acceptance_criteria' => null,
                'uiux_md' => 0.50,
                'design_creation_md' =>  0.50,
                'development_md' => 1.00,
                'qa_testing_md' => 0.50,
                'qa_testing_responsive_md' => 0.25,
                'translation_md' => 0.25,
            ],
            [
                'masterlist_module_type_id' => 3,
                'masterlist_function_type_id' => 15,
                'function_name' => null,
                'ox' => 1,
                'screen_count' => null,
                'acceptance_criteria' => 'Handle Errors, Import Summary Display, Fixed Template',
                'uiux_md' => 0.25,
                'design_creation_md' =>  0.63,
                'development_md' => 1.00,
                'qa_testing_md' => 0.25,
                'qa_testing_responsive_md' => 0.13,
                'translation_md' => 0.03,
            ],
            [
                'masterlist_module_type_id' => 3,
                'masterlist_function_type_id' => 16,
                'function_name' => null,
                'ox' => 1,
                'screen_count' => null,
                'acceptance_criteria' => 'Handle Errors, Export Summary Display, Fixed Template',
                'uiux_md' => 0.25,
                'design_creation_md' =>  0.63,
                'development_md' => 0.75,
                'qa_testing_md' => 0.25,
                'qa_testing_responsive_md' => 0.13,
                'translation_md' => 0.03,
            ],
            [
                'masterlist_module_type_id' => 3,
                'masterlist_function_type_id' => 17,
                'function_name' => 'File upload',
                'ox' => 1,
                'screen_count' => null,
                'acceptance_criteria' => 'File Types includes image files, docx, excel, pdf only',
                'uiux_md' => 0.25,
                'design_creation_md' =>  0.63,
                'development_md' => 1.25,
                'qa_testing_md' => 0.09,
                'qa_testing_responsive_md' => 0.06,
                'translation_md' => 0.00,
            ],
            [
                'masterlist_module_type_id' => 3,
                'masterlist_function_type_id' => 18,
                'function_name' => 'Reviews',
                'ox' => 1,
                'screen_count' => 1.00,
                'acceptance_criteria' => 'Can add and remove comments',
                'uiux_md' => 0.25,
                'design_creation_md' =>  0.63,
                'development_md' => 2.50,
                'qa_testing_md' => 0.19,
                'qa_testing_responsive_md' => 0.09,
                'translation_md' => 0.25,
            ],
            [
                'masterlist_module_type_id' => 5,
                'masterlist_function_type_id' => 19,
                'function_name' => 'Purchase History',
                'ox' => 1,
                'screen_count' => 1.0,
                'acceptance_criteria' => 'List only',
                'uiux_md' => 0.38,
                'design_creation_md' =>  0.88,
                'development_md' => 1.00,
                'qa_testing_md' => 0.25,
                'qa_testing_responsive_md' => 0.13,
                'translation_md' => 0.13,
            ],
            [
                'masterlist_module_type_id' => 5,
                'masterlist_function_type_id' => 19,
                'function_name' => 'Product List',
                'ox' => 1,
                'screen_count' => 1.0,
                'acceptance_criteria' => null,
                'uiux_md' => 0.38,
                'design_creation_md' =>  0.88,
                'development_md' => 1.50,
                'qa_testing_md' => 0.25,
                'qa_testing_responsive_md' => 0.13,
                'translation_md' => 0.25,
            ],
            [
                'masterlist_module_type_id' => 5,
                'masterlist_function_type_id' => 19,
                'function_name' => 'Product Advanced Search',
                'ox' => 1,
                'screen_count' => 1.0,
                'acceptance_criteria' => null,
                'uiux_md' => 0.38,
                'design_creation_md' =>  0.75,
                'development_md' => 1.50,
                'qa_testing_md' => 0.25,
                'qa_testing_responsive_md' => 0.13,
                'translation_md' => 0.25,
            ],
            [
                'masterlist_module_type_id' => 5,
                'masterlist_function_type_id' => 19,
                'function_name' => 'Product Detail',
                'ox' => 1,
                'screen_count' => 1.0,
                'acceptance_criteria' => null,
                'uiux_md' => 0.50,
                'design_creation_md' =>  0.75,
                'development_md' => 0.75,
                'qa_testing_md' => 0.38,
                'qa_testing_responsive_md' => 0.19,
                'translation_md' => 0.25,
            ],
            [
                'masterlist_module_type_id' => 5,
                'masterlist_function_type_id' => 19,
                'function_name' => 'Product Variation',
                'ox' => 1,
                'screen_count' => null,
                'acceptance_criteria' => null,
                'uiux_md' => 0.50,
                'design_creation_md' =>  0.75,
                'development_md' => 0.75,
                'qa_testing_md' => 0.38,
                'qa_testing_responsive_md' => 0.19,
                'translation_md' => 0.00,
            ],
            [
                'masterlist_module_type_id' => 5,
                'masterlist_function_type_id' => 19,
                'function_name' => 'Product Inventory',
                'ox' => 1,
                'screen_count' => 1.0,
                'acceptance_criteria' => null,
                'uiux_md' => 0.50,
                'design_creation_md' =>  0.88,
                'development_md' => 1.00,
                'qa_testing_md' => 0.50,
                'qa_testing_responsive_md' => 0.25,
                'translation_md' => 0.25,
            ],
            [
                'masterlist_module_type_id' => 5,
                'masterlist_function_type_id' => 19,
                'function_name' => 'Payment Gateway',
                'ox' => 1,
                'screen_count' => null,
                'acceptance_criteria' => null,
                'uiux_md' => 0.50,
                'design_creation_md' =>  0.75,
                'development_md' => 1.00,
                'qa_testing_md' => 0.25,
                'qa_testing_responsive_md' => 0.13,
                'translation_md' => 0.00,
            ],
            [
                'masterlist_module_type_id' => 5,
                'masterlist_function_type_id' => 19,
                'function_name' => 'Manual Shipping Status Update',
                'ox' => 1,
                'screen_count' => 1.0,
                'acceptance_criteria' => null,
                'uiux_md' => 0.38,
                'design_creation_md' =>  0.75,
                'development_md' => 0.75,
                'qa_testing_md' => 0.38,
                'qa_testing_responsive_md' => 0.19,
                'translation_md' => 0.25,
            ],
            [
                'masterlist_module_type_id' => 5,
                'masterlist_function_type_id' => 19,
                'function_name' => 'Inventory Integration (API)',
                'ox' => 1,
                'screen_count' => null,
                'acceptance_criteria' => null,
                'uiux_md' => 0.38,
                'design_creation_md' =>  0.50,
                'development_md' => 1.75,
                'qa_testing_md' => 0.00,
                'qa_testing_responsive_md' => 0.00,
                'translation_md' => 0.00,
            ],
            [
                'masterlist_module_type_id' => 5,
                'masterlist_function_type_id' => 19,
                'function_name' => 'Shipping Service Integration',
                'ox' => 1,
                'screen_count' => null,
                'acceptance_criteria' => null,
                'uiux_md' => 0.38,
                'design_creation_md' =>  0.88,
                'development_md' => 1.75,
                'qa_testing_md' => 0.00,
                'qa_testing_responsive_md' => 0.00,
                'translation_md' => 0.00,
            ],
            [
                'masterlist_module_type_id' => 5,
                'masterlist_function_type_id' => 19,
                'function_name' => 'Shipping Tracking',
                'ox' => 1,
                'screen_count' => 1.0,
                'acceptance_criteria' => null,
                'uiux_md' => 0.38,
                'design_creation_md' =>  0.88,
                'development_md' => 1.25,
                'qa_testing_md' => 0.25,
                'qa_testing_responsive_md' => 0.13,
                'translation_md' => 0.25,
            ],
            [
                'masterlist_module_type_id' => 6,
                'masterlist_function_type_id' => 20,
                'function_name' => 'with Basic Widgets',
                'ox' => 1,
                'screen_count' => 1.0,
                'acceptance_criteria' => null,
                'uiux_md' => 0.63,
                'design_creation_md' =>  0.25,
                'development_md' => 1.25,
                'qa_testing_md' => 0.19,
                'qa_testing_responsive_md' => 0.13,
                'translation_md' => 0.13,
            ],
            [
                'masterlist_module_type_id' => 6,
                'masterlist_function_type_id' => 21,
                'function_name' => 'with Special Widgets',
                'ox' => 1,
                'screen_count' => 1.0,
                'acceptance_criteria' => null,
                'uiux_md' => 1.50,
                'design_creation_md' =>  0.38,
                'development_md' => 1.25,
                'qa_testing_md' => 0.25,
                'qa_testing_responsive_md' => 0.13,
                'translation_md' => 0.13,
            ],
            [
                'masterlist_module_type_id' => 7,
                'masterlist_function_type_id' => 22,
                'function_name' => 'Create Message',
                'ox' => 1,
                'screen_count' => 1.0,
                'acceptance_criteria' => null,
                'uiux_md' => 0.25,
                'design_creation_md' =>  0.63,
                'development_md' => 1.00,
                'qa_testing_md' => 0.75,
                'qa_testing_responsive_md' => 0.50,
                'translation_md' => 0.25,
            ],
            [
                'masterlist_module_type_id' => 7,
                'masterlist_function_type_id' => 22,
                'function_name' => 'Inbox',
                'ox' => 1,
                'screen_count' => 1.0,
                'acceptance_criteria' => null,
                'uiux_md' => 0.38,
                'design_creation_md' =>  0.63,
                'development_md' => 0.75,
                'qa_testing_md' => 0.38,
                'qa_testing_responsive_md' => 0.19,
                'translation_md' => 0.25,
            ],
            [
                'masterlist_module_type_id' => 7,
                'masterlist_function_type_id' => 22,
                'function_name' => 'Outbox',
                'ox' => 1,
                'screen_count' => null,
                'acceptance_criteria' => null,
                'uiux_md' => 0.38,
                'design_creation_md' =>  0.63,
                'development_md' => 0.75,
                'qa_testing_md' => 0.38,
                'qa_testing_responsive_md' => 0.19,
                'translation_md' => 0.25,
            ],
            [
                'masterlist_module_type_id' => 7,
                'masterlist_function_type_id' => 22,
                'function_name' => 'Trash',
                'ox' => 1,
                'screen_count' => 1.0,
                'acceptance_criteria' => null,
                'uiux_md' => 0.38,
                'design_creation_md' =>  0.63,
                'development_md' => 0.75,
                'qa_testing_md' => 0.38,
                'qa_testing_responsive_md' => 0.19,
                'translation_md' => 0.25,
            ],
            [
                'masterlist_module_type_id' => 7,
                'masterlist_function_type_id' => 22,
                'function_name' => 'Conversation List',
                'ox' => 1,
                'screen_count' => null,
                'acceptance_criteria' => null,
                'uiux_md' => 0.38,
                'design_creation_md' =>  0.63,
                'development_md' => 1.00,
                'qa_testing_md' => 0.38,
                'qa_testing_responsive_md' => 0.19,
                'translation_md' => 0.25,
            ],
            [
                'masterlist_module_type_id' => 8,
                'masterlist_function_type_id' => 23,
                'function_name' => 'Change language (JP-EN)',
                'ox' => 1,
                'screen_count' => 1.0,
                'acceptance_criteria' => null,
                'uiux_md' => 0.13,
                'design_creation_md' =>  0.13,
                'development_md' => 0.50,
                'qa_testing_md' => 0.13,
                'qa_testing_responsive_md' => 0.19,
                'translation_md' => 0.00,
            ],
            [
                'masterlist_module_type_id' => 9,
                'masterlist_function_type_id' => 24,
                'function_name' => 'ETL Only (5 to 20 fields)',
                'ox' => 1,
                'screen_count' => null,
                'acceptance_criteria' => null,
                'uiux_md' => 0.13,
                'design_creation_md' =>  0.75,
                'development_md' => 2.50,
                'qa_testing_md' => 0.38,
                'qa_testing_responsive_md' => 0.25,
                'translation_md' => 0.25,
            ],
            [
                'masterlist_module_type_id' => 10,
                'masterlist_function_type_id' => 25,
                'function_name' => null,
                'ox' => 1,
                'screen_count' => 1.0,
                'acceptance_criteria' => 'Extension Creation, Linkage to actual system',
                'uiux_md' => 0.13,
                'design_creation_md' =>  0.63,
                'development_md' => 3.00,
                'qa_testing_md' => 0.25,
                'qa_testing_responsive_md' => 0.13,
                'translation_md' => 0.00,
            ],
            [
                'masterlist_module_type_id' => 11,
                'masterlist_function_type_id' => 26,
                'function_name' => null,
                'ox' => 1,
                'screen_count' => 2.0,
                'acceptance_criteria' => null,
                'uiux_md' => 0.50,
                'design_creation_md' =>  0.25,
                'development_md' => 2.50,
                'qa_testing_md' => 0.50,
                'qa_testing_responsive_md' => 0.25,
                'translation_md' => 0.25,
            ],
        ];

        MasterListFunction::insert($data);
    }
}
